import React from 'react';
import io from 'socket.io-client';
import Head from 'next/head';

let socket: any;

export default function LedPage() {
  const [buttonStatus, setButtonStatus] = React.useState(false);

  React.useEffect(() => {
    socketInitializer();
  }, []);

  const socketInitializer = async () => {
    await fetch('/api/socket');
    socket = io();

    socket.on('connect', () => {
      console.log('connected');
    });

    // socket.on('led-status', (data: number) => {
    //   setButt

    // });
  };

  const handleLed = (status: boolean) => {
    socket.emit('turn-led', { status: status ? 0 : 1 });
    setButtonStatus(!status);
  };
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full min-h-screen flex justify-center items-center'>
        <button
          className={`px-3 py-1 shadow-md rounded ${
            buttonStatus ? 'bg-green-500' : 'bg-red-500'
          } text-white text-lg font-semibold`}
          onClick={() => handleLed(buttonStatus)}
        >
          {buttonStatus ? 'On' : 'Off'}
        </button>
      </main>
    </div>
  );
}
