import React from 'react';
import io from 'socket.io-client';
import Head from 'next/head';

let socket: any;

export default function DashboardPage() {
  const [messageFromSocket, setMessageFromSocket] = React.useState(['']);

  React.useEffect(() => {
    socketInitializer();
  }, []);

  const socketInitializer = async () => {
    await fetch('/api/socket');
    socket = io();

    socket.on('connect', () => {
      console.log('connected');
    });

    socket.on('broadcast-new-user', (message: string) => {
      setMessageFromSocket((prevState) => [
        ...prevState,
        `dari server: ${message}`,
      ]);
    });
  };

  const handleEmit = () => {
    socket.emit('new-user', 'hallo');
  };
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>{messageFromSocket.map((message) => message)}</main>
      <button onClick={() => handleEmit()}>hayo</button>
    </div>
  );
}
